"""Model profiles and GPU topologies: what is served, and how the A100 is carved (D-40). Standard library only.

    deploy/models/<name>.json   one model: pinned checkpoint, architecture (for the fit), vLLM args, client sampling
    deploy/serving.json         the GPU, the engine settings every model shares, the two topologies, the fit gate

    python -m serving.profiles list
    python -m serving.profiles render qwen3-30b-a3b-2507-awq full --out .cache/deploy   # k8s/vllm.yaml + prefetch.sh

Model and topology are independent switches. Every model gets the same engine settings (context, batch, prefix
caching, memory share), so a comparison between profiles is a comparison between models, not engine configs.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MODELS = ROOT / "deploy" / "models"
SERVING = ROOT / "deploy" / "serving.json"
MANIFEST = ROOT / "deploy" / "k8s" / "vllm.yaml"
DEFAULT = ("qwen3-8b-awq", "sliced")            # the pair committed as deploy/k8s/vllm.yaml
PLANS = ("baseline", "round-1", "round-2", "paper-only")
REQUIRED = {"name": str, "plan": str, "summary": str, "hf": dict, "arch": dict, "serve": dict, "client": dict, "evidence": str, "caveats": list}
ARCH = ("layers", "attn_layers", "kv_heads", "head_dim", "hidden", "intermediate", "params_b", "active_params_b", "weights_gib")
LINEAR = ("layers", "key_heads", "key_head_dim", "value_heads", "value_head_dim", "conv_kernel")
CLIENT = {"temperature", "top_p", "top_k", "min_p", "repetition_penalty", "presence_penalty", "chat_template_kwargs"}
# Flags every profile shares come from serving.json; a profile may not override them.
ENGINE_OWNED = ("--model", "--revision", "--served-model-name", "--host", "--port", "--max-model-len", "--gpu-memory-utilization",
                "--max-num-seqs", "--max-num-batched-tokens", "--enable-prefix-caching", "--enable-auto-tool-choice")


def load_serving() -> dict:
    return json.loads(SERVING.read_text())


def load_profile(name: str) -> dict:
    path = MODELS / f"{name}.json"
    if not path.is_file():
        raise SystemExit(f"no profile {name!r}; have: {', '.join(p['name'] for p in profiles())}")
    p = json.loads(path.read_text())
    errs = validate_profile(p, path.stem)
    if errs:
        raise SystemExit(f"{path}: " + "; ".join(errs))
    return p


def profiles() -> list[dict]:
    """Every profile, baseline first, then by plan."""
    ps = [json.loads(p.read_text()) for p in sorted(MODELS.glob("*.json"))]
    return sorted(ps, key=lambda p: (PLANS.index(p["plan"]) if p.get("plan") in PLANS else 9, p["name"]))


def validate_profile(p: dict, stem: str) -> list[str]:
    errs = [f"{k} must be {t.__name__}" for k, t in REQUIRED.items() if not isinstance(p.get(k), t)]
    if errs:
        return errs
    if p["name"] != stem:
        errs.append(f"name {p['name']!r} must match the file name")
    if p["plan"] not in PLANS:
        errs.append(f"plan must be one of {PLANS}")
    if not (isinstance(p["hf"].get("repo"), str) and len(p["hf"].get("revision", "")) == 40):
        errs.append("hf needs repo and a pinned 40-character revision")
    errs += [f"arch.{k} must be a positive number" for k in ARCH if not (isinstance(p["arch"].get(k), int | float) and p["arch"][k] > 0)]
    lin = p["arch"].get("linear")
    if lin is not None:
        errs += [f"arch.linear.{k} must be a positive integer" for k in LINEAR if not (isinstance(lin.get(k), int) and lin[k] > 0)]
        if lin.get("layers", 0) + p["arch"].get("attn_layers", 0) != p["arch"].get("layers"):
            errs.append("arch: attn_layers + linear.layers must equal layers")
    elif p["arch"].get("attn_layers") != p["arch"].get("layers"):
        errs.append("arch: attn_layers < layers needs arch.linear (the recurrent layers)")
    if not isinstance(p["serve"].get("served_name"), str) or not isinstance(p["serve"].get("args"), list):
        errs.append("serve needs served_name and args")
    else:
        errs += [f"serve.args may not set {a.split('=')[0]} (serving.json owns it)" for a in p["serve"]["args"]
                 if a.split("=")[0] in ENGINE_OWNED]
    errs += [f"client.{k} is not a known sampling setting" for k in set(p["client"]) - CLIENT]
    return errs


TEMPLATE = """\
# GENERATED by `make render MODEL={name} TOPO={topo}` (serving/profiles.py). Edit deploy/models/{name}.json or
# deploy/serving.json, not this file. The committed deploy/k8s/vllm.yaml is the default pair; a test keeps it in sync.
#
# vLLM workers: a StatefulSet so each worker has a stable name (vllm-0, vllm-1) the gateway can pick by; a headless
# Service gives each one DNS (vllm-0.vllm.default.svc). Cluster-internal only: no hostPort, no NodePort, no
# LoadBalancer. Reach it with `make tunnel`.
#
# Model {name}: {summary}.
# Topology {topo}: {purpose}.
# Each replica gets {gpumem:,} MiB and {cores} % of the SMs through HAMi; at most {max_replicas} replica(s). Start with 1;
# `make scale N=...` adds workers. Fit: `make fit MODEL={name} TOPO={topo}`.
apiVersion: v1
kind: Service
metadata:
  name: vllm
  labels: {{app: vllm}}
spec:
  clusterIP: None
  selector: {{app: vllm}}
  ports:
    - {{name: http, port: 8000, targetPort: 8000}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vllm
  labels: {{app: vllm, doctor.serving/model: {name}, doctor.serving/topology: {topo}}}
spec:
  serviceName: vllm
  replicas: 1
  podManagementPolicy: Parallel
  selector:
    matchLabels: {{app: vllm}}
  template:
    metadata:
      labels: {{app: vllm, doctor.serving/model: {name}, doctor.serving/topology: {topo}}}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: /metrics
    spec:
      schedulerName: hami-scheduler
      terminationGracePeriodSeconds: 30
      containers:
        - name: vllm
          image: {image}
          imagePullPolicy: IfNotPresent
          args:
            - --model={repo}
            - --revision={revision}
            - --served-model-name={served}
            - --host=0.0.0.0
            - --port=8000
            - --max-model-len={max_model_len}          # audits reach ~15k tokens (D-29 amended); KV is allocated on demand
            - --gpu-memory-utilization={util}       # of what HAMi exposes to the pod: the slice, or the whole card
            - --max-num-seqs={max_num_seqs}
            - --max-num-batched-tokens={max_num_batched_tokens}
            - --enable-prefix-caching
            - --enable-auto-tool-choice
{model_args}
            - --enable-prompt-tokens-details   # usage.prompt_tokens_details.cached_tokens per request
            - --enable-request-id-headers      # echo X-Request-Id so traces join across hops
          env:
            - {{name: HF_HUB_OFFLINE, value: "1"}}          # weights are fetched by `make prefetch`; never download at serve time
            - {{name: HF_HOME, value: /root/.cache/huggingface}}
          ports:
            - {{name: http, containerPort: 8000}}
          resources:
            limits:
              nvidia.com/gpu: "1"
              nvidia.com/gpumem: "{gpumem}"     # MiB of the A100's {gpu_mib}
              nvidia.com/gpucores: "{cores}"      # percent of SMs
          startupProbe:                      # load + CUDA graph capture can take minutes
            httpGet: {{path: /health, port: 8000}}
            periodSeconds: 10
            failureThreshold: 90
          readinessProbe:
            httpGet: {{path: /health, port: 8000}}
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - {{name: hf-cache, mountPath: /root/.cache/huggingface}}
            - {{name: shm, mountPath: /dev/shm}}
      volumes:
        - name: hf-cache
          hostPath: {{path: /opt/hf-cache, type: Directory}}
        - name: shm
          emptyDir: {{medium: Memory, sizeLimit: 2Gi}}
"""

PREFETCH = """\
#!/usr/bin/env bash
# GENERATED by serving/profiles.py: fetch {repo}@{revision} into the node's HF cache (run as root on the node).
# The same container and marker as the boot-time fetch in deploy/cloud-init.yaml, so nothing is downloaded twice.
set -euo pipefail
MARK=/var/lib/bootstrap/model-{revision}
if [ -f "$MARK" ]; then echo "already fetched: {repo}@{revision}"; exit 0; fi
mkdir -p /opt/hf-cache
k3s ctr -n k8s.io run --rm --net-host \\
  --mount "type=bind,src=/opt/hf-cache,dst=/root/.cache/huggingface,options=rbind:rw" \\
  "{image}" "hf-fetch-$$" \\
  python3 -c 'from huggingface_hub import snapshot_download as d; print(d("{repo}", revision="{revision}", allow_patterns={patterns}))'
touch "$MARK"
"""


def topology(s: dict, topo: str) -> dict:
    if topo not in s["topologies"]:
        raise SystemExit(f"no topology {topo!r}; have: {', '.join(s['topologies'])}")
    return s["topologies"][topo]


def render_manifest(p: dict, topo: str, s: dict | None = None) -> str:
    s = s or load_serving()
    t, e = topology(s, topo), s["engine"]
    return TEMPLATE.format(name=p["name"], topo=topo, summary=p["summary"], purpose=t["purpose"], gpumem=t["gpumem_mib"],
                           cores=t["gpucores"], max_replicas=t["max_replicas"], image=e["image"], repo=p["hf"]["repo"],
                           revision=p["hf"]["revision"], served=p["serve"]["served_name"], max_model_len=e["max_model_len"],
                           util=e["gpu_memory_utilization"], max_num_seqs=e["max_num_seqs"],
                           max_num_batched_tokens=e["max_num_batched_tokens"], gpu_mib=s["gpu"]["mib"],
                           model_args="\n".join(f"            - {a}" for a in p["serve"]["args"]))


def render_prefetch(p: dict, s: dict | None = None) -> str:
    s = s or load_serving()
    patterns = p["hf"].get("allow_patterns")
    return PREFETCH.format(repo=p["hf"]["repo"], revision=p["hf"]["revision"], image=s["engine"]["image"],
                           patterns=json.dumps(patterns) if patterns else "None")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("list")
    r = sub.add_parser("render")
    r.add_argument("model")
    r.add_argument("topology")
    r.add_argument("--out", help="directory for k8s/vllm.yaml and prefetch.sh (default: the manifest on stdout)")
    f = sub.add_parser("field", help="print one profile field, e.g. serve.served_name")
    f.add_argument("model")
    f.add_argument("path")
    a = ap.parse_args(argv)
    if a.cmd == "list":
        for p in profiles():
            print(f"{p['name']:26} {p['plan']:10} {p['hf']['repo']}")
        return 0
    p = load_profile(a.model)
    if a.cmd == "field":
        v = p
        for k in a.path.split("."):
            v = v[k]
        print(v if isinstance(v, str) else json.dumps(v))
        return 0
    s = load_serving()
    manifest = render_manifest(p, a.topology, s)
    if not a.out:
        sys.stdout.write(manifest)
        return 0
    out = Path(a.out)
    (out / "k8s").mkdir(parents=True, exist_ok=True)
    (out / "k8s" / "vllm.yaml").write_text(manifest)
    (out / "prefetch.sh").write_text(render_prefetch(p, s))
    print(f"rendered {a.model} on {a.topology} → {out}/k8s/vllm.yaml, {out}/prefetch.sh")
    return 0


if __name__ == "__main__":
    sys.exit(main())
